Recent works and Projects sections
Halo-Lab/static-site pull request #5
Opened 2021-05-17 09:29 UTC by ElenaGrasovskaya

The current version contains no animation, except some hovers.

2021-05-17 10:37 UTC, YevhenKap requested changes

2021-05-17 10:37 UTC, YevhenKap commented on src/styles/index.scss
> +  color: #ccccd2;
Треба помітити якось, щоб ми знали, що даний колір унікальний і можливо треба буде обговорити це з дизайнером.

2021-05-17 10:37 UTC, YevhenKap commented on src/styles/index.scss
> +    color: white;
Тут треба взяти колір з `_colors.scss` - там є такий колір.

2021-05-17 10:37 UTC, YevhenKap commented on src/styles/index.scss
> +  border-top-left-radius: 50% 50%;
Тут можна просто вказати `border-radius: 50%;`

2021-05-17 10:37 UTC, YevhenKap commented on src/styles/index.scss
> +  background-color: lightgrey;
Знову ж таки колір треба брати з `_colors.scss`. Якщо там такого немає, то винести у змінну у даному файлі (бажано). Занадто велика палітра теж погано, це треба буде обговорити. Я теж, правда, лишав у градієнтах "сирий колір" 🤔 Мабуть, затягувати з цим не варто)

2021-05-17 10:37 UTC, YevhenKap commented on src/styles/index.scss
> +    color: white;
Тут те ж саме.

2021-05-17 10:37 UTC, YevhenKap commented on src/pages/index.11ty.js
> +        <div class="recent-works-block">
Гадаю, тут можна винести шляхи у data-файл та зробити окремий шаблон генерації блоків іконок.

2021-05-17 10:40 UTC, ElenaGrasovskaya commented on src/styles/index.scss
> +    color: white;
виправлю

2021-05-17 10:40 UTC, ElenaGrasovskaya commented on src/styles/index.scss
> +  color: #ccccd2;
Це я взяла з оригіналу halo-lab.com може його просто додати до _colors.scss?

2021-05-17 10:43 UTC, ElenaGrasovskaya commented on src/styles/index.scss
> +  border-top-left-radius: 50% 50%;
випралю

2021-05-17 10:43 UTC, ElenaGrasovskaya commented on src/styles/index.scss
> +  background-color: lightgrey;
я не знайша сірий градієнт, додати теж?

2021-05-17 10:59 UTC, ElenaGrasovskaya commented on src/pages/index.11ty.js
> +        <div class="recent-works-block">
Якщо чесно я не дуже розумію як

2021-05-17 11:00 UTC, ElenaGrasovskaya commented on src/styles/index.scss
> +    color: white;
виправила

2021-05-17 13:24 UTC, YevhenKap commented on src/styles/index.scss
> +  background-color: lightgrey;
Ні, най буде вже так.

2021-05-17 13:24 UTC, YevhenKap commented on src/styles/index.scss
> +  color: #ccccd2;
Якщо він тільки тут треба, то немає сенсу виносити в `_colors.scss`

2021-05-17 13:25 UTC, YevhenKap commented on src/pages/index.11ty.js
> +        <div class="recent-works-block">
Ок. Потім зробимо. Треба не забутись)

2021-05-17 14:20 UTC, ElenaGrasovskaya commented on src/styles/index.scss
> +  color: #ccccd2;
Він секції Projects зустрічається 6 разів... а Projects взагалі модуль який ще викликається з дропдаун меню у хедері... треба його буде відокремити та імпортувати в індекс

2021-05-18 06:26 UTC, YevhenKap requested changes
Там є два файли, які конфліктують з `develop`. Це якраз `index.11ty.js` та `index.scss`. Виріш його, будь ласка.

2021-05-18 06:26 UTC, YevhenKap commented on src/styles/index.scss
> +    -webkit-transform: rotate(360deg);
У збірці стоїть `autoprefixer` і він це зробить сам. Та і префікс до даної властивості вже неактуально писати.

2021-05-18 06:47 UTC, ElenaGrasovskaya commented on src/styles/index.scss
> +    -webkit-transform: rotate(360deg);
видалила

2021-05-18 07:50 UTC, merged